#!bash

HASH=`git rev-parse HEAD`
URL="https://filebin.denis.no/" 
FILE="$HOME/gopath/bin/filebin"
echo "Binary: ${FILE}"

CHECKSUM=$(sha256sum ${FILE} | cut -d ' ' -f1)
echo "Checksum: ${CHECKSUM}"

/usr/bin/curl -v --data-binary "@${FILE}" "${URL}" -H "Filename: filebin-${HASH}" -H "Tag: filebinbuilds" -H "Content-SHA256: ${CHECKSUM}"
